# Tensorfaktorierung

In [11]:
import numpy as np
# Vektoren definieren
u = [3, 1, 2]
v = [4, 0, 3]
w = [2, 3]
# Berechnung des dyadischen Produkts
np.outer(u,v)

array([[12,  0,  9],
       [ 4,  0,  3],
       [ 8,  0,  6]])

In [12]:
#Berechnung des äusseren Produkts
np.einsum('i,j->ij', u,v)
# i ist der index für den ersten vektor, 
# j ist derjenige des zweiten Vektores

array([[12,  0,  9],
       [ 4,  0,  3],
       [ 8,  0,  6]])

In [13]:
# wenn man teile weglässt wird das Produkt nur aufsummiert 
np.einsum('i,j->j', u,v)

array([24,  0, 18])

In [14]:
# Für Tensor erzeugen, weiteren index hinzufügen 
np.einsum('i,j,k -> kij', u,v,w)

array([[[24,  0, 18],
        [ 8,  0,  6],
        [16,  0, 12]],

       [[36,  0, 27],
        [12,  0,  9],
        [24,  0, 18]]])

In [7]:
import tensorly as tl
import numpy as np

In [12]:
# Matrix machen
A = np.zeros((2,2))
A[0,0] =2 
A[0,1] =1
A[1,0] =1 
A[1,1] =3 
B = np.zeros((2,2))
B[0,0] = 3 
B[0,1] = 3
B[1,0] = -2 
B[1,1] = 4 

In [13]:
tl.tenalg.kronecker((A, B))

array([[ 6.,  6.,  3.,  3.],
       [-4.,  8., -2.,  4.],
       [ 3.,  3.,  9.,  9.],
       [-2.,  4., -6., 12.]])

In [14]:
tl.tenalg.khatri_rao((A, B))

array([[ 6.,  3.],
       [-4.,  4.],
       [ 3.,  9.],
       [-2., 12.]])

In [15]:
# Hadamard-Produkt
A*B

array([[ 6.,  3.],
       [-2., 12.]])