## k-Nächste-Nachbarn
- Modell aufsetzen und trainieren (Kreuzvalidierung)
```
from sklearn.neighbors import KNeighborsClassifier as knn
from sklearn.model_selection import train_test_split as split
from sklearn.metrics import accuracy_score as score
x_train, x_test, y_train, y_test = split(data[:,:2], data[:,2], test_size=0.2)
model = knn(n_neighbors=k)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
score(y_test, y_pred)
````
Beispiel: Bonität (Datei 'credit.txt'): Alter, Einkommen, Bonität

In [3]:
from sklearn.neighbors import KNeighborsClassifier as knn
# automatischer split, wählt die Trainings/Test-daten zufällig aus 
from sklearn.model_selection import train_test_split as split 
from sklearn.metrics import accuracy_score as score

import numpy as np
import matplotlib.pyplot as plt
# Reihenfolge des Paketladens ist nicht relevant 

In [10]:
# daten laden
data = np.loadtxt("credit.txt", delimiter=",")
data

array([[ 52.,  23.,   0.],
       [ 46.,  75.,   1.],
       [ 29.,  30.,   1.],
       [ 55.,  42.,   0.],
       [ 39.,  47.,   0.],
       [ 65.,  26.,   0.],
       [ 74.,  54.,   1.],
       [ 57.,  76.,   1.],
       [ 45.,  85.,   1.],
       [ 52.,  18.,   0.],
       [ 42.,  83.,   1.],
       [ 20.,  27.,   0.],
       [ 64.,  83.,   1.],
       [ 58.,  64.,   1.],
       [ 53.,  53.,   0.],
       [ 47.,  70.,   1.],
       [ 37.,  38.,   0.],
       [ 49.,  95.,   0.],
       [ 66.,  95.,   1.],
       [ 39.,  72.,   1.],
       [ 45.,  21.,   0.],
       [ 40.,  49.,   0.],
       [ 54.,  75.,   1.],
       [ 59.,  78.,   1.],
       [ 22.,  43.,   0.],
       [ 50.,  84.,   0.],
       [ 65.,  62.,   0.],
       [ 44.,  83.,   1.],
       [ 35.,  44.,   0.],
       [ 70., 102.,   1.],
       [ 58.,  37.,   1.],
       [ 38.,  78.,   1.],
       [ 51.,  47.,   0.],
       [ 57., 103.,   1.],
       [ 64.,  37.,   1.],
       [ 54.,  71.,   1.],
       [ 46.,  55.,   1.],
 

In [14]:
# Daten automatisch aufsplitten lassen 80% Train, 20% Test
x_train, x_test, y_train, y_test = split(data[:,:2], data[:,2], test_size=0.2)
x_train

array([[ 42.,  83.],
       [ 44.,  83.],
       [ 29.,  62.],
       [ 50.,  58.],
       [ 52.,  18.],
       [ 54.,  71.],
       [ 45.,  19.],
       [ 59.,  82.],
       [ 57., 103.],
       [ 42.,  51.],
       [ 74.,  54.],
       [ 66.,  17.],
       [ 70., 102.],
       [ 53.,  36.],
       [ 55.,  64.],
       [ 47.,  45.],
       [ 54.,  75.],
       [ 57.,  76.],
       [ 49.,  23.],
       [ 20.,  27.],
       [ 46.,  75.],
       [ 50.,  46.],
       [ 54.,  84.],
       [ 37.,  38.],
       [ 62.,  90.],
       [ 22.,  43.],
       [ 64.,  37.],
       [ 49.,  95.],
       [ 33.,   8.],
       [ 33.,  44.],
       [ 30.,  33.],
       [ 64.,  83.],
       [ 58.,  83.],
       [ 40.,  49.],
       [ 29.,  42.],
       [ 43.,  49.],
       [ 47.,  70.],
       [ 46.,  55.],
       [ 51.,  47.],
       [ 29.,  30.],
       [ 41.,  59.],
       [ 31.,  38.],
       [ 44.,  62.],
       [ 54.,  44.],
       [ 66.,  95.],
       [ 67.,  55.],
       [ 54.,  47.],
       [ 59.,

In [17]:
# Model erstellen (anzahl neighbours eingeben, kleinen Wert, default = 5)
model = knn(n_neighbors=5)
# Model trainieren
model.fit(x_train, y_train)

KNeighborsClassifier()

In [21]:
# Vorhersage in y_pred speichern (mit Befehl predict)
y_pred = model.predict(x_test)

In [32]:
# vorhersagen vergleichen 
print("Tatsächliche Werte: ",y_test)
print("Vorhersagen       : ",y_pred)
# Score anzeigen
print("Score")
print("Der Score",score(y_test, y_pred))


Tatsächliche Werte:  [1. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 1.]
Vorhersagen       :  [1. 0. 0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 0. 1.]
Score
Der Score 0.8571428571428571


Bestimmung des optimalen k-Werts aus [1, n]
```for k in range(1,16):
model = knn(n_neighbors=k)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print(k, ":", score(y_test, y_pred))
```
Frage: welche Werte für k sinnvoll…?

und welche Bonität hat nun unsere Person (57) mit 37'000 CHF Einkommen…?
``` model.predict([[57., 37.]]) 15 niedrig```

In [33]:
for k in range(1,16):
    model = knn(n_neighbors=k)
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    print("für K-Wert =",k, ":", score(y_test, y_pred))

für K-Wert = 1 : 0.7857142857142857
für K-Wert = 2 : 0.8571428571428571
für K-Wert = 3 : 0.8571428571428571
für K-Wert = 4 : 0.7857142857142857
für K-Wert = 5 : 0.8571428571428571
für K-Wert = 6 : 0.8571428571428571
für K-Wert = 7 : 0.8571428571428571
für K-Wert = 8 : 0.8571428571428571
für K-Wert = 9 : 0.8571428571428571
für K-Wert = 10 : 0.8571428571428571
für K-Wert = 11 : 0.8571428571428571
für K-Wert = 12 : 0.8571428571428571
für K-Wert = 13 : 0.8571428571428571
für K-Wert = 14 : 0.8571428571428571
für K-Wert = 15 : 0.8571428571428571


> Diese Werte sind Abhängig vom Split und sollten sich leicht verändern wenn ein anderer gewählt wird

> **Wenn der Datensatz grösser ist, sollten die Zahlen weniger schwanken bei unterschiedlichen splits**

und welche Bonität hat nun unsere Person (57) mit 37'000 CHF Einkommen…?

> model.predict([[57., 37.]])→ niedrig

In [34]:
model.predict([[57., 37.]])

array([0.])